// GENERATED by scripts/sync-vercel-function.mjs from src/server/contact.ts. Do not edit by hand:
// change the source, then run "npm run sync:api". Vercel Function, runs automatically on Vercel.
/**
 * Contact form handler, shared by every host.
 * It only uses web-standard APIs (fetch, Response), so the same code runs on
 * Cloudflare Pages Functions, Vercel, Netlify and Node.
 */

interface MailEnv {
  RESEND_API_KEY?: string;
  /** Where messages are delivered. */
  CONTACT_TO?: string;
  /** Sender shown to you, on a domain verified in Resend, e.g. "Skandava Website <website@skandava.com>". */
  CONTACT_FROM?: string;
}

const DEFAULT_TO = 'hariprasad@skandava.com';

interface Payload { name: string; email: string; phone: string; message: string }

const json = (status: number, body: Record<string, unknown>) =>
  new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' } });

const clean = (v: unknown, max: number) => (typeof v === 'string' ? v.trim().slice(0, max) : '');
const oneLine = (v: string) => v.replace(/[\r\n]+/g, ' ');
const escapeHtml = (v: string) => v.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

function validate(raw: unknown): { ok: true; data: Payload } | { ok: false; error: string } {
  if (!raw || typeof raw !== 'object') return { ok: false, error: 'Invalid request.' };
  const b = raw as Record<string, unknown>;
  const data: Payload = { name: clean(b.name, 100), email: clean(b.email, 200), phone: clean(b.phone, 40), message: clean(b.message, 5000) };
  if (data.name.length < 2) return { ok: false, error: 'Please enter your name.' };
  if (!EMAIL.test(data.email)) return { ok: false, error: 'Please enter a valid email address.' };
  if (data.message.length < 10) return { ok: false, error: 'Please tell us a little more (at least 10 characters).' };
  return { ok: true, data };
}

async function handleContact(request: Request, env: MailEnv): Promise<Response> {
  if (request.method !== 'POST') return json(405, { ok: false, error: 'Method not allowed.' });

  let body: unknown;
  try { body = await request.json(); } catch { return json(400, { ok: false, error: 'Invalid request.' }); }

  // Spam traps: bots fill the hidden field or submit instantly. Answer "ok" so they learn nothing.
  const trap = body as Record<string, unknown>;
  if (clean(trap?.website, 200) !== '' || (typeof trap?.t === 'number' && trap.t < 2500)) return json(200, { ok: true });

  const parsed = validate(body);
  if (!parsed.ok) return json(400, { ok: false, error: parsed.error });
  const { name, email, phone, message } = parsed.data;

  if (!env.RESEND_API_KEY) {
    console.error('[contact] RESEND_API_KEY is not set');
    return json(500, { ok: false, error: 'Email is not configured yet.' });
  }

  const to = env.CONTACT_TO || DEFAULT_TO;
  const from = env.CONTACT_FROM || 'Skandava Website <onboarding@resend.dev>';
  const subject = `New enquiry from ${oneLine(name)}`;
  const text = `Name: ${name}\nEmail: ${email}\nPhone: ${phone || '-'}\n\n${message}`;
  const html = `<div style="font-family:-apple-system,Segoe UI,Arial,sans-serif;font-size:15px;line-height:1.55;color:#1d1d1f">
    <p><strong>New enquiry from the Skandava website</strong></p>
    <p><strong>Name:</strong> ${escapeHtml(name)}<br><strong>Email:</strong> <a href="mailto:${escapeHtml(email)}">${escapeHtml(email)}</a><br><strong>Phone:</strong> ${escapeHtml(phone || '-')}</p>
    <p style="white-space:pre-wrap;border-left:3px solid #d2d2d7;padding-left:12px">${escapeHtml(message)}</p>
  </div>`;

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { Authorization: `Bearer ${env.RESEND_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ from, to: [to], reply_to: email, subject, text, html }),
    });
    if (!res.ok) {
      console.error('[contact] Resend error', res.status, await res.text());
      return json(502, { ok: false, error: 'We could not send your message right now.' });
    }
    return json(200, { ok: true });
  } catch (err) {
    console.error('[contact] network error', err);
    return json(502, { ok: false, error: 'We could not send your message right now.' });
  }
}

declare const process: { env: Record<string, string | undefined> };

export function POST(request: Request) {
  return handleContact(request, process.env);
}
